![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [6]:
import numpy as np

my_array = np.arange(0,10)
print("Orden original:", my_array)

print("Elementos solicitados:", my_array[my_array % 2 != 0][::-1])

Orden original: [0 1 2 3 4 5 6 7 8 9]
Elementos solicitados: [9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
print("Elementos solicitados:", my_array[8:6:-1])

Elementos solicitados: [8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [10]:
print("Elementos solicitados:", my_array[2::-1])

Elementos solicitados: [2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [16]:
matriz_4x5 = np.arange(1,21).reshape(4,5)
print("Matrix original:")
print(matriz_4x5)
print("___________________________________________________")

matriz_4x5_invertida_filas = np.flip(matriz_4x5, axis=0)
print("Filas invertidas:")
print(matriz_4x5_invertida_filas)
print("___________________________________________________")


matriz_4x5_invertida_columnas = np.flip(matriz_4x5, axis=1)
print("Columnas invertidas:")
print(matriz_4x5_invertida_columnas)

Matrix original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
___________________________________________________
Filas invertidas:
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
___________________________________________________
Columnas invertidas:
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
print("_____________________________________________")
print("Matriz original:")
matriz_ejercicio_4 = np.arange(1,21).reshape(4,5)
print(matriz_ejercicio_4)

print("_____________________________________________")
print("Matriz modificada:")
matriz_modificada = matriz_ejercicio_4[0:2,0:2]
print(matriz_modificada)

_____________________________________________
Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
_____________________________________________
Matriz modificada:
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [23]:
print("_____________________________________________")
print("Matriz original:")
matriz_ejercicio_4 = np.arange(1,21).reshape(4,5)
print(matriz_ejercicio_4)

print("_____________________________________________")
print("Matriz modificada:")
matriz_modificada = matriz_ejercicio_4[0::2,0::2]
print(matriz_modificada)

_____________________________________________
Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
_____________________________________________
Matriz modificada:
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [25]:
print("_____________________________________________")
print("Matriz original:")
matriz_ejercicio_4 = np.arange(1,21).reshape(4,5)
print(matriz_ejercicio_4)

print("_____________________________________________")
print("Matriz modificada:")
matriz_modificada = np.flip(matriz_ejercicio_4, axis=1)[0:3]
print(matriz_modificada)

_____________________________________________
Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
_____________________________________________
Matriz modificada:
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [28]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

solucion_1 = x[x == "Loro"]
print(solucion_1)

solucion_2 = x[np.char.equal(x, "Loro")]
print(solucion_2)


['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [30]:
ejer_9 = np.arange(1,21)
print(ejer_9)

ejer_9_reshaped = ejer_9.reshape(2,5,2)
print(ejer_9_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [32]:
ejer_10 = np.full(10, 0)
print(ejer_10)

ejer_10[3] = 1
print(ejer_10)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [35]:
ejer_11 = np.arange(10,50)
print(ejer_11)

ejer_11 = ejer_11[::-1]
print(ejer_11)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [40]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)


def get_indices_donde_no_haya_un_cero(vector: np.ndarray):
    indexes = np.where(vector != 0)[0]
    return indexes

indices_donde_no_hay_un_cero = get_indices_donde_no_haya_un_cero(ejer_12)
print(indices_donde_no_hay_un_cero)

[1 2 0 0 4 0]
[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [6]:
ejer_13 = np.random.randint(0,100, size=(10,10))
print(ejer_13)

print("Num máximo:", np.max(ejer_13))
print("Num mínimo:", np.min(ejer_13))

[[56 89 95 74 41 89 29 11 75 58]
 [32 35 80 55 94 73 57 70 56 51]
 [28 12 27 65 18  0 62 18 78 39]
 [25  9 35 44 27 95 66  3 37 49]
 [ 7 94 32  2 34 99 10  3 71 18]
 [46 91 66 82 32 59 74 98 63 23]
 [35 46  2 94 55 65 81 13 64 22]
 [59 87 49 35 65 47 60 59 99 90]
 [10 40 18 36 55 37 77  9 58 51]
 [27 55 36 71 89  5  7 24 80  0]]
Num máximo: 99
Num mínimo: 0


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [8]:
ejer_14 = np.random.random(30)
print(ejer_14)

print("Media del vector:", np.mean(ejer_14))

[0.70432385 0.79533333 0.73330905 0.07878303 0.83419304 0.74279268
 0.0059292  0.26239206 0.11929174 0.60766321 0.76611474 0.38617766
 0.32706077 0.83571298 0.04725415 0.54479504 0.36795416 0.99663143
 0.54342023 0.94299967 0.63387883 0.55567185 0.62055447 0.39339276
 0.23564537 0.4912113  0.46729566 0.5639088  0.82082009 0.01029051]
Media del vector: 0.5144933885763276


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [23]:
ejer_15 = np.full((12,12), 0)
ejer_15[0, :] = 1
ejer_15[-1, :] = 1
ejer_15[:, 0] = 1
ejer_15[:, -1] = 1

print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [30]:
ejer_16 = np.full((8,8), 0)

ejer_16[0::2, 1::2] = 1
ejer_16[1::2, 0::2] = 1
print(ejer_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
ejer_17_base = np.array([[0,1],[1,0]])
print(ejer_17_base)

ejer_17 = np.tile(ejer_17_base, (4,4))
print(ejer_17)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [39]:
ejer_18 = np.random.randint(0, 99, (5, 5))
print(ejer_18)

media = np.mean(ejer_18)
print("Media", media)

desviacion_estandar = np.std(ejer_18)
print("Desviación estándar:", desviacion_estandar)

ejer_18_normalizada = (ejer_18[:,:] - media) / desviacion_estandar
print(ejer_18_normalizada)


[[44 89 72 64 38]
 [28 65 97 76  4]
 [83 96 26 31 29]
 [95 23  1 51 11]
 [53 91 98 46 30]]
Media 53.64
Desviación estándar: 30.61356562048923
[[-0.31489308  1.1550435   0.59973413  0.33841207 -0.51088463]
 [-0.8375372   0.37107732  1.41636556  0.73039515 -1.62150338]
 [ 0.95905196  1.3837003  -0.90286771 -0.73954143 -0.80487194]
 [ 1.35103504 -1.00086349 -1.71949915 -0.08623628 -1.39284657]
 [-0.02090576  1.22037402  1.44903082 -0.24956257 -0.77220668]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
secuencia = np.arange(0,11)
print(secuencia)

secuencia_2 = secuencia.copy()
secuencia_2[(secuencia_2 >= 3) & (secuencia_2 <= 8)] = -1
print(secuencia_2)

secuencia_3 = secuencia.copy()
secuencia_3[(secuencia_3 >= 3) & (secuencia_3 <= 8)] *= -1 ## Hola Andrea! Aquí considero que negar quiere decir cambiar el signo del entero como hemos hablado ;) 
print(secuencia_3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
